POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto ",
    "number": 123456
}
###

POST https://bitter-snow-9585.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Aagsdfasg",
    "number": "sdasfadf"
}
###

POST https://bitter-snow-9585.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "sdasfadf"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "sdasfadf"
}
###


POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "lol",
    "number": "1233455678899"
}
###


POST https://bitter-snow-9585.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123-123456789"
}
###